### ISSUE TITLE
Mixolydian Key seems to be broken

### ISSUE THREAD

**Issue by bwl21** [PencilCode/musical.js#3]
If you play this, it sounds a bit weird. But if you replace the Key by "F" then it sounds ok.
I am not that firm with respect of keys, I only can hear the problem. If you wanna hear how the tune goes, listen to : http://www.youtube.com/watch?v=O_k7sXvt8cc

X:4841
T:Once I had a sweetheart
O:england
C:anon.
M:3/4
L:1/8
K:Cmix
Q:120
G2|"C"(ED) C3 C|"Bb"B B3 B2|"F"(AG) F2 A2|"C"G6|"C"z4:|c2|
"C"(cG3) B2|"F"(AG) F3 A|"Bb"(BD3) F2|"C"(DC) C4|"C"z4 C2|
"Cm"(cd_e2) d2|"Gm"(cB) G3 F|"Cm"G2 C2 "Gm"B,2|"C"C6-|"C"C6|]

To be honest, i think this is not extremely important, since there is a workaround. You may fix it for completeness

**Comment by davidbau** [comment]
This is fixed!
